<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{a9ed13f8-7010-4aa8-be47-ba11eca525c0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
a : INT;
b : INT;
c : INT;
d : INT;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[c := a+b;
d := c+a;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>